version: '3.7'
services:
  app:
    image: strund3r/fatesg-eventos
    ports:
      - "80:80"
  db:
    image: postgres:9.6
    volumes:
      - db-data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_DB=eventos
    ports:
      - "5432:5432"
volumes:
  db-data:
    driver: local